#!/bin/bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN="${BASE_DIR}/build/libllvm_sda_pass.so"
LOGGER="${BASE_DIR}/build/CMakeFiles/logger_obj.dir/src/logger.cpp.o"
SERIALIZER="${BASE_DIR}/build/serializer/libserializer.a"
INC_DIR="${BASE_DIR}/inc"
SERIALIZER_INC_DIR="${BASE_DIR}/libs/serializer/inc"
DYNINFO_INC_DIR="${BASE_DIR}/libs/dynamic_info/inc"
PROTO_INC="${BASE_DIR}/build/serializer/generated"

if ! pkg-config --exists protobuf absl_log_internal_message; then
    echo "Error: protobuf or absl-log-internal-message not found via pkg-config."
    echo "Ensure they are installed and PKG_CONFIG_PATH is set."
    exit 1
fi

PROTO_LIBS=$(pkg-config --libs protobuf)
ABSL_LIBS=$(pkg-config --libs absl_log_internal_message absl_log_internal_nullguard absl_hash absl_city absl_raw_hash_set)

OPT_LEVEL="-O0"
INPUT_FILE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -i)
            INPUT_FILE="$2"
            shift 2
            ;;
        -O0|-O1|-O2|-O3|-Os|-Oz)
            OPT_LEVEL="$1"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: ./llsda -i <file.cpp> [-O2]"
            exit 1
            ;;
    esac
done

if [[ -z "$INPUT_FILE" ]]; then
    echo "Error: No input file provided."
    echo "Usage: ./llsda -i <file.cpp> [-O2]"
    exit 1
fi

PROGRAM_NAME=$(basename -- "$INPUT_FILE")
OUTPUT_NAME="${PROGRAM_NAME%.*}.out"

echo "--- LLSDA: Compiling $INPUT_FILE with $OPT_LEVEL ---"

clang++ -std=c++20 \
    -fpass-plugin="${PLUGIN}" \
    -fno-discard-value-names \
    "$INPUT_FILE" \
    "${LOGGER}" \
    "${SERIALIZER}" \
    ${PROTO_LIBS} \
    ${ABSL_LIBS} \
    -lpthread \
    -I"${INC_DIR}" \
    -I"${PROTO_INC}" \
    -I"${SERIALIZER_INC_DIR}" \
    -I"${DYNINFO_INC_DIR}" \
    "${OPT_LEVEL}" \
    -o "${OUTPUT_NAME}"

if [ $? -eq 0 ]; then
    echo "--- Success: Generated ${OUTPUT_NAME} ---"
else
    echo "--- Failure: Compilation failed ---"
    exit 1
fi